name: yandex_go_scooters
description: "The Yandex systems sharing project as part of a student camp from Yandex and the Higher School of Economics."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # ML и обработка изображений
  onnxruntime: ^1.4.1
  image: ^4.0.17
  
  # Работа с камерой и галереей
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  
  # Разрешения
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: YandexSansText
      fonts:
        - asset: assets/fonts/YandexSansText-Thin.ttf
          weight: 300
        - asset: assets/fonts/YandexSansText-Light.ttf
          weight: 400
        - asset: assets/fonts/YandexSansText-Regular.ttf
          weight: 500
        - asset: assets/fonts/YandexSansText-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/YandexSansText-Medium.ttf
          weight: 600
        - asset: assets/fonts/YandexSansText-Bold.ttf
          weight: 700

  assets:
    - assets/images/logo.png
    - assets/models/mobilenetv3_large.onnx
    # - assets/models/model2.onnx  # Раскомментировать когда добавится